export const ApiRoutes = {
  auth: '/auth',
  users: '/users',
  vendors: '/vendors',
  listings: '/listings',
  search: '/search',
  bookings: '/bookings',
  payments: '/payments',
  inventory: '/inventory',
  pricing: '/pricing',
  crm: '/crm',
  operations: '/operations',
  notifications: '/notifications',
  ai: '/ai',
  community: '/community',
  trustSafety: '/trust-safety',
  adventure: '/adventure-os',
  transport: '/transport',
  whatsappCommerce: '/whatsapp-commerce',
  admin: '/admin',
  audit: '/audit',
} as const;
