export type FeatureSurface = 'traveler' | 'provider' | 'admin';

export type FeatureDefinition = {
  slug: string;
  surface: FeatureSurface;
  eyebrow: string;
  title: string;
  summary: string;
  primaryMetric: string;
  workflow: string[];
  modules: string[];
};

export const travelerFeatures: Record<string, FeatureDefinition> = {
  discover: {
    slug: 'discover',
    surface: 'traveler',
    eyebrow: 'Destination discovery',
    title: 'Explore verified places, local operators, and seasonal ideas.',
    summary: 'Curated destination shelves combine stays, treks, taxis, events, safety notes, and provider trust signals.',
    primaryMetric: '42 curated destination clusters',
    workflow: ['Pick a region', 'Compare trusted supply', 'Save to trip workspace'],
    modules: ['Trending destinations', 'Provider trust', 'Local experiences', 'Safety filters'],
  },
  search: {
    slug: 'search',
    surface: 'traveler',
    eyebrow: 'Smart search',
    title: 'Search by intent across stays, taxis, treks, guides, and trips.',
    summary: 'Keyword, map, semantic, and safety-aware filters help travelers find bookable inventory without bouncing between apps.',
    primaryMetric: 'Unified travel inventory',
    workflow: ['Describe the trip', 'Filter by dates and trust', 'Book or plan'],
    modules: ['Semantic ranking', 'Geo filters', 'Budget bands', 'Availability'],
  },
  map: {
    slug: 'map',
    surface: 'traveler',
    eyebrow: 'Map search',
    title: 'Plan around distance, pickup points, safety, and nearby supply.',
    summary: 'A map-first workspace connects destinations, routes, transport, emergency support, and marketplace listings.',
    primaryMetric: 'Live route context',
    workflow: ['Choose map area', 'Inspect nearby supply', 'Add route stops'],
    modules: ['Nearby stays', 'Certified taxis', 'SOS zones', 'Route timing'],
  },
  listing: {
    slug: 'listing',
    surface: 'traveler',
    eyebrow: 'Listing detail',
    title: 'Inspect verified inventory with media, prices, policies, and trust.',
    summary: 'Listing pages expose amenities, availability, host credentials, cancellation terms, reviews, and checkout readiness.',
    primaryMetric: 'Bookable listing profile',
    workflow: ['Review details', 'Check availability', 'Lock inventory'],
    modules: ['Media gallery', 'Policies', 'Reviews', 'Escrow checkout'],
  },
  provider: {
    slug: 'provider',
    surface: 'traveler',
    eyebrow: 'Provider storefront',
    title: 'Browse a verified provider storefront before booking.',
    summary: 'Storefronts collect business verification, listings, guide teams, vehicles, stories, and support channels.',
    primaryMetric: 'Provider trust profile',
    workflow: ['Review business', 'Compare listings', 'Message or book'],
    modules: ['KYC status', 'All inventory', 'Team profile', 'Support'],
  },
  'trip-planner': {
    slug: 'trip-planner',
    surface: 'traveler',
    eyebrow: 'AI trip planner',
    title: 'Build itineraries that synchronize stays, activities, and taxis.',
    summary: 'The planner converts dates, budget, interests, and group size into a travel blueprint with verified supply.',
    primaryMetric: 'Itinerary in under 30 seconds',
    workflow: ['Enter trip intent', 'Review AI blueprint', 'Book matched services'],
    modules: ['Stays', 'Activities', 'Certified taxis', 'Budget planner'],
  },
  trips: {
    slug: 'trips',
    surface: 'traveler',
    eyebrow: 'Trip workspace',
    title: 'Manage upcoming journeys, collaborators, bookings, and tasks.',
    summary: 'Trips collect itinerary items, payment status, group decisions, documents, memories, and safety actions.',
    primaryMetric: 'One workspace per journey',
    workflow: ['Open trip', 'Coordinate group', 'Track journey'],
    modules: ['Itinerary', 'Group planning', 'Documents', 'Alerts'],
  },
  booking: {
    slug: 'booking',
    surface: 'traveler',
    eyebrow: 'Booking detail',
    title: 'Track lifecycle, payments, support, and provider handoff.',
    summary: 'Booking pages show inventory locks, escrow state, cancellation policy, support events, and check-in milestones.',
    primaryMetric: 'Escrow-backed booking',
    workflow: ['Confirm status', 'Contact provider', 'Complete check-in'],
    modules: ['Lifecycle', 'Payments', 'Support', 'Refunds'],
  },
  wallet: {
    slug: 'wallet',
    surface: 'traveler',
    eyebrow: 'Traveler wallet',
    title: 'Handle balances, refunds, rewards, and split payments.',
    summary: 'Wallet tools keep traveler funds, refunds, coupons, GST invoices, and group contributions auditable.',
    primaryMetric: 'Refund-ready ledger',
    workflow: ['Review balance', 'Apply offers', 'Track refunds'],
    modules: ['Wallet balance', 'Coupons', 'Invoices', 'Split pay'],
  },
  wishlist: {
    slug: 'wishlist',
    surface: 'traveler',
    eyebrow: 'Wishlist',
    title: 'Save trusted listings and compare them by trip intent.',
    summary: 'Wishlists organize stays, activities, taxis, providers, and public itineraries for future planning.',
    primaryMetric: 'Saved travel shortlist',
    workflow: ['Save item', 'Compare options', 'Move to trip'],
    modules: ['Saved stays', 'Saved treks', 'Saved taxis', 'Notes'],
  },
  community: {
    slug: 'community',
    surface: 'traveler',
    eyebrow: 'Community',
    title: 'Find reviews, stories, groups, creators, and verified local advice.',
    summary: 'Community features connect traveler content with moderation, creator storefronts, and bookable recommendations.',
    primaryMetric: 'Moderated travel graph',
    workflow: ['Browse stories', 'Join group', 'Book recommendations'],
    modules: ['Posts', 'Reviews', 'Groups', 'Creators'],
  },
  memories: {
    slug: 'memories',
    surface: 'traveler',
    eyebrow: 'Memories',
    title: 'Turn trips into journals, media collections, and shareable stories.',
    summary: 'The memory layer captures itinerary context, photos, notes, and AI-assisted recaps after travel.',
    primaryMetric: 'Trip journal timeline',
    workflow: ['Import media', 'Generate recap', 'Share story'],
    modules: ['Timeline', 'Media vault', 'AI recap', 'Sharing'],
  },
  safety: {
    slug: 'safety',
    surface: 'traveler',
    eyebrow: 'Traveler safety',
    title: 'Access SOS, emergency contacts, live sharing, and safety guidance.',
    summary: 'Safety tools connect location sharing, verified providers, emergency playbooks, and support escalation.',
    primaryMetric: 'Emergency-ready trip',
    workflow: ['Add contacts', 'Share live location', 'Escalate SOS'],
    modules: ['SOS', 'Contacts', 'Women-safe filters', 'Incident support'],
  },
};

export const providerFeatures: Record<string, FeatureDefinition> = {
  dashboard: {
    slug: 'dashboard',
    surface: 'provider',
    eyebrow: 'Provider Operating System',
    title: 'Manage bookings, inventory, staff, fleet, pricing, payouts, and growth.',
    summary: 'A command center for local travel businesses that combines marketplace demand with daily operations.',
    primaryMetric: '6 operating modules live',
    workflow: ['Review today', 'Resolve tasks', 'Grow revenue'],
    modules: ['Booking command center', 'Smart price calendar', 'Lead inbox', 'Payout tracker', 'Fleet and staff ops', 'Growth signals'],
  },
  onboarding: {
    slug: 'onboarding',
    surface: 'provider',
    eyebrow: 'Vendor onboarding',
    title: 'Create a provider business with roles, services, and compliance.',
    summary: 'Guided onboarding captures business identity, service categories, owner profile, and first operating modules.',
    primaryMetric: 'Provider setup checklist',
    workflow: ['Add business', 'Choose modules', 'Invite team'],
    modules: ['Business profile', 'Service categories', 'Owner account', 'Team roles'],
  },
  kyc: {
    slug: 'kyc',
    surface: 'provider',
    eyebrow: 'KYC and compliance',
    title: 'Submit documents and track verification status.',
    summary: 'KYC workflows collect documents, tax details, bank metadata, and admin review notes before publishing.',
    primaryMetric: 'Pending review queue',
    workflow: ['Upload documents', 'Resolve issues', 'Unlock storefront'],
    modules: ['Documents', 'Bank details', 'Tax profile', 'Review notes'],
  },
  listings: {
    slug: 'listings',
    surface: 'provider',
    eyebrow: 'Listing management',
    title: 'Manage stays, activities, transport, guides, and experiences.',
    summary: 'Providers can create, publish, price, and moderate every bookable service from one inventory workspace.',
    primaryMetric: 'Multi-category catalog',
    workflow: ['Create listing', 'Add media', 'Publish supply'],
    modules: ['Accommodation', 'Activities', 'Transport', 'Media'],
  },
  inventory: {
    slug: 'inventory',
    surface: 'provider',
    eyebrow: 'Inventory',
    title: 'Control availability and protect against overbooking.',
    summary: 'Inventory tools synchronize direct stock, channel metadata, allocation rules, and booking locks.',
    primaryMetric: 'Overbooking guard active',
    workflow: ['Set units', 'Sync channels', 'Reserve safely'],
    modules: ['Availability', 'Channel sync', 'Locks', 'Allocations'],
  },
  bookings: {
    slug: 'bookings',
    surface: 'provider',
    eyebrow: 'Bookings',
    title: 'Operate confirmations, check-ins, cancellations, and support.',
    summary: 'The booking command center makes lifecycle state, traveler details, payment status, and staff tasks visible.',
    primaryMetric: 'Lifecycle command center',
    workflow: ['Accept booking', 'Coordinate service', 'Close stay'],
    modules: ['Arrivals', 'Escrow state', 'Cancellations', 'Support'],
  },
  calendar: {
    slug: 'calendar',
    surface: 'provider',
    eyebrow: 'Calendar',
    title: 'Plan occupancy, slots, events, and seasonal blocks.',
    summary: 'Calendar views tie availability, pricing rules, guide rosters, vehicle dispatch, and maintenance blocks together.',
    primaryMetric: 'Unified operations calendar',
    workflow: ['View demand', 'Adjust supply', 'Publish changes'],
    modules: ['Occupancy', 'Slots', 'Roster', 'Blocks'],
  },
  pricing: {
    slug: 'pricing',
    surface: 'provider',
    eyebrow: 'Dynamic pricing',
    title: 'Tune rates using occupancy, festivals, demand, and discounts.',
    summary: 'Pricing recommendations explain signals, guard minimum rates, and prepare changes for channel publishing.',
    primaryMetric: 'AI rate suggestions',
    workflow: ['Review signal', 'Approve rate', 'Measure uplift'],
    modules: ['Rate rules', 'Demand signals', 'Discounts', 'Competitors'],
  },
  staff: {
    slug: 'staff',
    surface: 'provider',
    eyebrow: 'Staff',
    title: 'Manage roles, attendance, rosters, and provider permissions.',
    summary: 'Staff operations connect task ownership, role-based access, shifts, attendance, and performance visibility.',
    primaryMetric: 'Role-scoped team access',
    workflow: ['Invite staff', 'Assign shifts', 'Track tasks'],
    modules: ['Roles', 'Attendance', 'Rosters', 'Tasks'],
  },
  operations: {
    slug: 'operations',
    surface: 'provider',
    eyebrow: 'Operations',
    title: 'Coordinate housekeeping, maintenance, incidents, and internal work.',
    summary: 'Operations boards help teams assign work, record incidents, escalate support, and maintain service quality.',
    primaryMetric: 'Assigned task board',
    workflow: ['Create task', 'Assign owner', 'Close with evidence'],
    modules: ['Housekeeping', 'Maintenance', 'Incidents', 'Internal messages'],
  },
  fleet: {
    slug: 'fleet',
    surface: 'provider',
    eyebrow: 'Fleet',
    title: 'Operate taxis, drivers, routes, fuel, and certified dispatch.',
    summary: 'Fleet management tracks vehicles, driver documents, ride allocation, GPS adapters, and zero-commission payout rules.',
    primaryMetric: 'Certified dispatch desk',
    workflow: ['Verify driver', 'Dispatch ride', 'Settle payout'],
    modules: ['Vehicles', 'Drivers', 'Routes', 'Fuel'],
  },
  adventure: {
    slug: 'adventure',
    surface: 'provider',
    eyebrow: 'Adventure OS',
    title: 'Run treks, slots, guides, equipment, waivers, and risk checks.',
    summary: 'Adventure operators get slot capacity, guide assignment, kit allocation, waiver tracking, and emergency readiness.',
    primaryMetric: 'Waiver-aware slots',
    workflow: ['Create slot', 'Assign guide', 'Check safety'],
    modules: ['Trek slots', 'Guides', 'Equipment', 'Waivers'],
  },
  crm: {
    slug: 'crm',
    surface: 'provider',
    eyebrow: 'CRM',
    title: 'Capture leads, segments, follow-ups, loyalty, and referrals.',
    summary: 'CRM tools convert marketplace, WhatsApp, and campaign demand into scored leads and repeat customers.',
    primaryMetric: 'Lead scoring active',
    workflow: ['Capture lead', 'Segment audience', 'Follow up'],
    modules: ['Contacts', 'Segments', 'Follow-ups', 'Referrals'],
  },
  marketing: {
    slug: 'marketing',
    surface: 'provider',
    eyebrow: 'Marketing',
    title: 'Launch campaigns across WhatsApp, email, creators, and offers.',
    summary: 'Marketing workflows connect audience selection, content, marketplace offers, attribution, and campaign events.',
    primaryMetric: 'Campaign automation',
    workflow: ['Choose audience', 'Send campaign', 'Track revenue'],
    modules: ['Campaigns', 'Offers', 'Creators', 'Attribution'],
  },
  payouts: {
    slug: 'payouts',
    surface: 'provider',
    eyebrow: 'Payouts',
    title: 'Track escrow, settlements, refunds, invoices, and wallet credits.',
    summary: 'Finance views expose ledger-backed payouts, tax invoices, settlement holds, and dispute impacts.',
    primaryMetric: 'Ledger-backed settlement',
    workflow: ['Validate check-in', 'Release settlement', 'Reconcile ledger'],
    modules: ['Escrow', 'Wallet', 'Invoices', 'Refunds'],
  },
  analytics: {
    slug: 'analytics',
    surface: 'provider',
    eyebrow: 'Analytics',
    title: 'Measure demand, conversion, revenue, operations, and trust.',
    summary: 'Analytics summarize marketplace performance, occupancy, pricing impact, campaign quality, and trust scores.',
    primaryMetric: 'Provider growth score',
    workflow: ['Review trend', 'Find bottleneck', 'Act on signal'],
    modules: ['Revenue', 'Occupancy', 'Conversion', 'Trust'],
  },
  settings: {
    slug: 'settings',
    surface: 'provider',
    eyebrow: 'Settings',
    title: 'Configure organization, roles, notifications, policies, and billing.',
    summary: 'Settings centralize provider account configuration, module permissions, payout setup, and operating policies.',
    primaryMetric: 'Organization controls',
    workflow: ['Set policy', 'Manage roles', 'Configure notifications'],
    modules: ['Organization', 'Roles', 'Policies', 'Billing'],
  },
  storefront: {
    slug: 'storefront',
    surface: 'provider',
    eyebrow: 'Storefront',
    title: 'Preview the public provider profile and bookable inventory.',
    summary: 'Storefront tools manage public brand, trusted supply, stories, reviews, and inquiry conversion.',
    primaryMetric: 'Public profile live',
    workflow: ['Preview profile', 'Optimize listings', 'Share storefront'],
    modules: ['Brand', 'Inventory', 'Reviews', 'Stories'],
  },
};

export const adminFeatures: Record<string, FeatureDefinition> = {
  overview: {
    slug: 'overview',
    surface: 'admin',
    eyebrow: 'Platform Admin',
    title: 'Govern trust, safety, vendors, payments, support, and AI operations.',
    summary: 'The admin surface gives platform teams the control room for marketplace quality, risk, finance, and growth.',
    primaryMetric: 'Governance modules online',
    workflow: ['Review queues', 'Resolve risk', 'Audit decisions'],
    modules: ['KYC review', 'Fraud monitoring', 'Refund approvals', 'AI moderation', 'Audit logs', 'Support control'],
  },
  users: {
    slug: 'users',
    surface: 'admin',
    eyebrow: 'User management',
    title: 'Manage traveler, provider, creator, staff, and admin accounts.',
    summary: 'User governance includes roles, sessions, devices, emergency contacts, and suspicious login signals.',
    primaryMetric: 'Identity control center',
    workflow: ['Find user', 'Review context', 'Apply action'],
    modules: ['Profiles', 'Roles', 'Sessions', 'Risk'],
  },
  vendors: {
    slug: 'vendors',
    surface: 'admin',
    eyebrow: 'Vendor management',
    title: 'Review provider businesses, trust scores, subscriptions, and supply.',
    summary: 'Vendor operations manage approvals, verification, service quality, subscriptions, and marketplace readiness.',
    primaryMetric: 'Provider approval queue',
    workflow: ['Review vendor', 'Check trust', 'Approve supply'],
    modules: ['Profiles', 'Trust scores', 'Subscriptions', 'Storefronts'],
  },
  kyc: {
    slug: 'kyc',
    surface: 'admin',
    eyebrow: 'KYC review',
    title: 'Verify documents, bank details, tax profile, and compliance notes.',
    summary: 'KYC governance gives reviewers document metadata, decision history, escalations, and publish gates.',
    primaryMetric: 'Compliance decision trail',
    workflow: ['Inspect document', 'Request fix', 'Approve provider'],
    modules: ['Documents', 'Bank review', 'Tax review', 'Notes'],
  },
  listings: {
    slug: 'listings',
    surface: 'admin',
    eyebrow: 'Listing moderation',
    title: 'Moderate marketplace supply for quality, safety, and accuracy.',
    summary: 'Admin listing tools review media, copy, categories, pricing anomalies, safety claims, and provider context.',
    primaryMetric: 'Moderation queue',
    workflow: ['Review listing', 'Flag issue', 'Publish or reject'],
    modules: ['Media', 'Content', 'Pricing', 'Safety claims'],
  },
  bookings: {
    slug: 'bookings',
    surface: 'admin',
    eyebrow: 'Booking oversight',
    title: 'Monitor lifecycle exceptions, disputes, cancellations, and support.',
    summary: 'Booking governance exposes state transitions, provider response, traveler support, and override audit trails.',
    primaryMetric: 'Exception queue',
    workflow: ['Inspect booking', 'Resolve exception', 'Audit action'],
    modules: ['Lifecycle', 'Disputes', 'Overrides', 'Support'],
  },
  payments: {
    slug: 'payments',
    surface: 'admin',
    eyebrow: 'Payments',
    title: 'Oversee orders, escrow, wallets, ledgers, and gateway events.',
    summary: 'Payment operations reconcile append-only events, immutable ledger entries, gateway callbacks, and fraud signals.',
    primaryMetric: 'Append-only payment events',
    workflow: ['Review event', 'Reconcile ledger', 'Escalate anomaly'],
    modules: ['Orders', 'Escrow', 'Wallets', 'Gateway events'],
  },
  refunds: {
    slug: 'refunds',
    surface: 'admin',
    eyebrow: 'Refund approvals',
    title: 'Approve refunds and disputes with policy and ledger context.',
    summary: 'Refund tools compare policy windows, traveler claims, provider evidence, settlement status, and audit records.',
    primaryMetric: 'Policy-aware refunding',
    workflow: ['Review claim', 'Compare policy', 'Approve refund'],
    modules: ['Claims', 'Evidence', 'Policy', 'Ledger'],
  },
  fraud: {
    slug: 'fraud',
    surface: 'admin',
    eyebrow: 'Fraud monitoring',
    title: 'Detect suspicious payments, logins, listings, reviews, and behavior.',
    summary: 'Fraud monitoring combines device, payment, content, provider, and booking signals for triage.',
    primaryMetric: 'Risk signal console',
    workflow: ['Review signal', 'Investigate actor', 'Apply control'],
    modules: ['Payment risk', 'Login risk', 'Listing risk', 'Review risk'],
  },
  'trust-safety': {
    slug: 'trust-safety',
    surface: 'admin',
    eyebrow: 'Trust and safety',
    title: 'Manage SOS, incidents, disputes, verified reviews, and safety badges.',
    summary: 'Trust teams coordinate incident reports, badge review, location-share escalation, disputes, and moderation.',
    primaryMetric: 'Safety response desk',
    workflow: ['Triage incident', 'Assign owner', 'Close safely'],
    modules: ['SOS', 'Incidents', 'Badges', 'Disputes'],
  },
  community: {
    slug: 'community',
    surface: 'admin',
    eyebrow: 'Community moderation',
    title: 'Moderate posts, reviews, creators, groups, and public itineraries.',
    summary: 'Community governance blends AI moderation, reviewer queues, creator quality, and marketplace integrity.',
    primaryMetric: 'Moderated content queue',
    workflow: ['Review content', 'Apply policy', 'Notify actor'],
    modules: ['Posts', 'Reviews', 'Creators', 'Groups'],
  },
  cms: {
    slug: 'cms',
    surface: 'admin',
    eyebrow: 'CMS',
    title: 'Manage destinations, editorial content, safety notes, and offers.',
    summary: 'CMS tools support destination content, travel advisories, campaign surfaces, and marketplace merchandising.',
    primaryMetric: 'Destination content studio',
    workflow: ['Draft content', 'Review safety', 'Publish destination'],
    modules: ['Destinations', 'Advisories', 'Offers', 'Editorial'],
  },
  subscriptions: {
    slug: 'subscriptions',
    surface: 'admin',
    eyebrow: 'Subscriptions',
    title: 'Control provider plans, commissions, trials, invoices, and renewals.',
    summary: 'Subscription governance manages provider billing models, marketplace commissions, entitlements, and collections.',
    primaryMetric: 'Provider revenue plans',
    workflow: ['Assign plan', 'Track usage', 'Collect billing'],
    modules: ['Plans', 'Commissions', 'Entitlements', 'Invoices'],
  },
  support: {
    slug: 'support',
    surface: 'admin',
    eyebrow: 'Support',
    title: 'Coordinate traveler, provider, payment, safety, and booking support.',
    summary: 'Support queues connect tickets, booking context, user history, escalation rules, and notification channels.',
    primaryMetric: 'Unified support inbox',
    workflow: ['Open ticket', 'Resolve context', 'Close with note'],
    modules: ['Tickets', 'Escalations', 'SLA', 'Notifications'],
  },
  'audit-logs': {
    slug: 'audit-logs',
    surface: 'admin',
    eyebrow: 'Audit logs',
    title: 'Inspect critical actions across payments, admin, KYC, and safety.',
    summary: 'Audit logs keep immutable decision history with actors, subjects, metadata, and request identifiers.',
    primaryMetric: 'Immutable action trail',
    workflow: ['Search actor', 'Inspect action', 'Export evidence'],
    modules: ['Actors', 'Subjects', 'Metadata', 'Exports'],
  },
  ai: {
    slug: 'ai',
    surface: 'admin',
    eyebrow: 'AI operations',
    title: 'Govern itinerary, pricing, moderation, recommendations, and cost.',
    summary: 'AI operations expose prompt versions, request logs, safety flags, high-impact approvals, and spend signals.',
    primaryMetric: 'AI governance console',
    workflow: ['Review request', 'Check safety', 'Approve model action'],
    modules: ['Itineraries', 'Pricing', 'Moderation', 'Cost'],
  },
  analytics: {
    slug: 'analytics',
    surface: 'admin',
    eyebrow: 'Platform analytics',
    title: 'Measure marketplace health, supply, demand, conversion, and risk.',
    summary: 'Analytics surface demand, provider quality, booking conversion, payment issues, search health, and support load.',
    primaryMetric: 'Marketplace command metrics',
    workflow: ['Read health', 'Find risk', 'Drive action'],
    modules: ['Demand', 'Supply', 'Conversion', 'Risk'],
  },
};

export function getTravelerFeature(slug: string) {
  return travelerFeatures[slug] ?? travelerFeatures.discover;
}

export function getProviderFeature(slug: string) {
  return providerFeatures[slug] ?? providerFeatures.dashboard;
}

export function getAdminFeature(slug: string) {
  return adminFeatures[slug] ?? adminFeatures.overview;
}
